name: Trigger automation-scripts-api workflow
 
on:
  push:
    branches:
      - main
jobs:
  trigger:
    if: "!contains(github.event.head_commit.message, '[skip tests]')"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger automation-scripts-api repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: nurture-with-care/automation-scripts-api
          event-type: run-automation-tests
 
