name: Trigger automation-scripts-api workflow
 
on:
  push:
    branches:
      - main
jobs:
  trigger:
    if: "!contains(github.event.head_commit.message, '[skip tests]')"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger automation-scripts-api repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Jitenderkr2791/automation-scripts-api
          event-type: run-automation-tests
          
      - name: Wait for 30 seconds to allow the workflow to start
        run: sleep 30

      - name: Poll triggered workflow status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const owner = 'jitenderkr2791';
            const repo = 'automation-scripts-api';
            const workflowName = 'CI/CD Pipeline'; // ✅ Replace with actual workflow name
            const maxRetries = 20;
            const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
            
            let attempt = 0;
            let workflowRun = null;

            while (attempt < maxRetries) {
              const runs = await github.rest.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                per_page: 10
              });

              workflowRun = runs.data.workflow_runs.find(
                run =>
                  run.name === workflowName &&
                  run.event === 'repository_dispatch' &&
                  new Date(run.created_at) > new Date(Date.now() - 10 * 60 * 1000) // within last 10 mins
              );

              if (!workflowRun) {
                console.log(`Attempt ${attempt + 1}: No matching workflow run found. Retrying...`);
                await delay(10000);
                attempt++;
                continue;
              }

              if (workflowRun.status === 'completed') {
                console.log(`✅ Workflow completed with conclusion: ${workflowRun.conclusion}`);
                if (workflowRun.conclusion !== 'success') {
                  core.setFailed(`❌ Triggered workflow failed with conclusion: ${workflowRun.conclusion}`);
                }
                break;
              } else {
                console.log(`⏳ Workflow status: ${workflowRun.status}. Retrying...`);
                await delay(10000);
                attempt++;
              }
            }

            if (!workflowRun || workflowRun.status !== 'completed') {
              core.setFailed('❌ Triggered workflow did not complete in expected time.');
            }
